# Generated by Django 3.2.5 on 2022-12-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210730_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
